### PR TITLE
Insert client connection data into PAM environment, upgraded

### PR DESCRIPTION
**Pull request by wardragon**
# Thank you for your contribution

You are welcome to open PR, but they are used for discussion only. All
patches must eventually go to the openvpn-devel mailing list for review:

* https://lists.sourceforge.net/lists/listinfo/openvpn-devel

Please send your patch using [git-send-email](https://git-scm.com/docs/git-send-email). For example to send your latest commit to the list:

    $ git send-email --to=openvpn-devel@lists.sourceforge.net HEAD~1

For details, see these Wiki articles:

* https://community.openvpn.net/openvpn/wiki/DeveloperDocumentation
* https://community.openvpn.net/openvpn/wiki/Contributing

### CODE REVIEW

**Comment by ordex** [comment]
@selvanair do you have any opinion about this change? By itself it seems to make sense, but I am not a PAM expert.

**Comment by selvanair** [comment]
I believe this is the same as the patch to the list from Paolo Cerrito wardragon78@gmail.com 

I have seen multiple versions of it which has languished for poor "quality" of the patch, though the content looks reasonable and worth having.

**Comment by selvanair** [comment]
found one: https://patchwork.openvpn.net/project/openvpn2/patch/20220624104940.2885435-1-wardragon78@gmail.com/ (looks like this is the latest, though I have about 7 versions of it in my inbox -- not sure why this is called v2).

**Comment by ordex** [comment]
OK, then I am closing this PR as it's not useful anymore. Any additional comment/feedback can be given on the mailing list. Thanks!

**Comment by wardragon** [comment]
ok, i have made same mistake with path number, latest working patch was this:

[Openvpn-devel,v2] Insert client connection data into PAM environment v2

at link:

https://patchwork.openvpn.net/project/openvpn2/patch/20220624104940.2885435-1-wardragon78@gmail.com/

and was rebased on master branch at the time was published. Changed from v1 is in the log function.
I hope now that there is no problem and could be merged.

And yes, the patch from this account is the same published on patchwork with the wardragon78@gmail.com.

Thanks

**Pull request closed without merging**
