### PR TITLE
Update contrib/pull-resolv-conf/client.up for no DOMAIN

### PR DESCRIPTION
**Pull request by jeffmcutter**
When no DOMAIN is received from push/pull, do not add either domain or search to the resolv.conf.
Fix typo in comment resolv.con[f].
Only add new line when using domain or search.

### CODE REVIEW

**Comment by syzzer** [comment]
Looks reasonable to me at first sight. However, OpenVPN's patch review process goes through a public mailinglist, not github pull requests. Could you please send your patch to openvpn-devel@lists.sourceforge.net?

(For more information on the development process, see https://community.openvpn.net/openvpn/wiki/DeveloperDocumentation. TL;DR: Use `git format-patch` to create a patch, then use `git send-email` to send it to the mailinglist.)

**Comment by mattock** [comment]
After a recent discussion the development team agreed that using PRs for code review is fine. The final, reviewed patch will still be sent to the list. @syzzer: do you ACK this patch? I could send it to the mailing list.

**Comment by syzzer** [comment]
@mattock: yes, and please do.

**Comment by mattock** [comment]
Patch sent to the list, waiting for merging.

**Comment by cron2** [comment]
this should have been closed a week ago, when David merged the patch... :-)

**Pull request closed without merging**
