### PR TITLE
Add link to bug tracker

### PR DESCRIPTION
**Pull request by leonklingele**
As `issue tracking` has been disabled for this repo here on Github, it would be great to include a link to the official OpenVPN issue tracking system.

### CODE REVIEW

**Comment by mattock** [comment]
I sent this to openvpn-devel mailing list as a patch. I'll close this PR once the patch is merged.

**Comment by cron2** [comment]
Wouldn't it be nice if PRs were closed after merging... @dsommers

**Comment by dsommers** [comment]
Absolutely!  I'll try to remember that!

**Comment by mattock** [comment]
I wonder if there is a way automatically close associated PRs with some magic Git commit log message... even now GitHub notices when a PR is referred to in the logs.

**Comment by schwabe** [comment]
Just append a (closes #25) in the commit message.

Example https://github.com/schwabe/ics-openvpn/issues/481 (https://github.com/schwabe/ics-openvpn/commit/9498eb76ef4c053d77e45d4d3ebaf839e0f40a0b)

**Pull request closed without merging**
