### PR TITLE
Simple change to allow hostname to be passed as an IV variable for DN…

### PR DESCRIPTION
**Pull request by ricardo-manriquez**
…S configuration on server

# Thank you for your contribution

You are welcome to open PR, but they are used for discussion only. All
patches must eventually go to the openvpn-devel mailing list for review:

* https://lists.sourceforge.net/lists/listinfo/openvpn-devel

Please send your patch using [git-send-email](https://git-scm.com/docs/git-send-email). For example to send your latest commit to the list:

    $ git send-email --to=openvpn-devel@lists.sourceforge.net HEAD~1

For details, see these Wiki articles:

* https://community.openvpn.net/openvpn/wiki/DeveloperDocumentation
* https://community.openvpn.net/openvpn/wiki/Contributing

### CODE REVIEW

**Comment by schwabe** [comment]
This should go to the mailing list as patch. Also this need some explaination why this should 

a) always be send (in contrast to only when `push-peer-info` is active
b) why a solution that passes this information as UV_ variable with `setenv UV_hostname something` in the configuration or `openvpn --config conf --setenv UV_hostname $(hostname)` is an acceptable solution

**Comment by ricardo-manriquez** [comment]
Hi thanks for taking my patch for review, I just read that I should send it to the mailing list, but I felt this initial approach was less obtrusive, this is my first time here I hope I'm not bothering

a) I placed the code so it only triggers when push-peer-info is active so as not to leak unwanted or new information just as the MAC address
b) I've tried the whole day to solve this in the way you suggest, but all the solutions bring me to the need of writing up scripts or changing mayor things at the openvpn-gui level, this seems to be requested enough, in the forums and stackoverflow, and I have not been able to find a solution that is clean and keeps the one "ovpn" file configuration. 

This is just a suggestion for a solution of a problem I stumbled upon. If you deem it acceptable I'm sending it to the mailing list as the documentation states.

Thank you very much for your time!

**Comment by ordex** [comment]
hey @ricardo-manriquez can you mail the final patch to the ml for proper discussion please?

**Comment by ordex** [comment]
Closing as it yet unclear why b) is not really an option while sending an IV_ is.
If you still feel this is a problem that needs to be solved, please mail the patch directly to the ml for further discussion.

**Pull request closed without merging**
