### PR TITLE
Updated URLs in README

### PR DESCRIPTION
**Pull request by Peppernrino**
Updated to current links, and added SSL to all.
Changed tap-windows to reflect NDIS 6 repository shift.

Read contributing guidelines. Will submit properly in a bit. :)

### CODE REVIEW

**Comment by cron2** [comment]
Generally speaking, the changes make sense.  We shouldn't link to "manual for version 2.0", though, but that's more a bug of the openvpn.net web site.

@mattock can you get that fixed?  Than we can get the URL redirect updated (2.4! or better), and change the URL in here accordingly.

Or we just keep the /man URL here, just changing to https.

**Comment by mattock** [comment]
I created a bunch of internal JIRA tickets, including one about this. I proposed keeping the /man URL and just pointing it to OpenVPN 2.4 man page. We should always keep it pointed to the latest version.

**Comment by bernhardreiter** [comment]
Seems these updates are ready to me made with the improvement of the link to the manual page. Any idea when it can be merged?

**Comment by cron2** [comment]
hi,

On Wed, Sep 11, 2019 at 08:25:15AM -0700, Bernhard E. Reiter wrote:
> Seems these updates are ready to me made with the improvement of the link to the manual page. Any idea when it can be merged?

Do we have patches on the list?

Github PRs are not merged.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Comment by flichtenheld** [comment]
Since some of the links are just wrong I plan to submit this patch to the mailing list as part of an initiative to clean up the Github PR submissions.

**Comment by ordex** [comment]
@flichtenheld was this sent to the ml? or not yet?

**Comment by flichtenheld** [comment]
> @flichtenheld was this sent to the ml? or not yet?

https://patchwork.openvpn.net/project/openvpn2/patch/20211107181252.17045-1-frank@lichtenheld.com/

**Comment by ordex** [comment]
Closing this PR as the discussion was moved to the mailing list.

**Pull request closed without merging**
