### PR TITLE
help/how2work added

### PR DESCRIPTION
**Pull request by johnthepepper**
Information about VPNs

### CODE REVIEW

**Comment by schwabe** [comment]
This is just some example code from https://www.geeksforgeeks.org/socket-programming-cc/amp/ This has nothing to do with OpenVPN.

**Comment by johnthepepper** [comment]
Are you read information in code? Coding process is not finished. And i wrote source code in geeksforgeeks.com but url is like malware code and bot deleted code (Url like this: geeksforgeeks.com/blabla/%27%27socket%27)

**Comment by cron2** [comment]
Please do not open PRs until the code is ready for inclusion in OpenVPN.

If it has nothing to do with OpenVPN, never open a PR for OpenVPN.

**Comment by johnthepepper** [comment]
Ohh sorry

**Comment by johnthepepper** [comment]
I don't know about this

**Pull request closed without merging**
