### PR TITLE
Change unix build instruction

### PR DESCRIPTION
**Pull request by ITJesse**

### CODE REVIEW

**Comment by mattock** [comment]
Hi,

The original build instruction are in fact correct when building from release tarballs. When building from Git you _do_ need autoreconf, but you can use this slightly simplified process:

    autoreconf -vi
    ./configure
    make
    make install

We can definitely take the patch if the above changes/concerns are addressed.

**Comment by selvanair** [comment]
To add to @mattock comment, it may be more useful to add a line on how to download and unpack the source tarball. Then ./configure && make && make install is all that is needed. Requiring developer tools such as autoconf for a "quick build" does not look right..

**Comment by mattock** [comment]
I suggest this minor modification:

```
To get the latest release of OpenVPN, go to:

    http://openvpn.net/

To Build and Install,

    tar -zxf openvpn-<version>.tar.gz
    ./configure
    make
    make install

or see the file INSTALL for more info.
```
This makes it clear the instructions are for the tarball, not Git sources.

**Comment by cron2** [comment]
Hi,

On Mon, May 30, 2016 at 12:35:34PM -0700, Samuli Seppänen wrote:
> I suggest this minor modification:

Sounds good.

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by mattock** [comment]
Patch sent to the list.

**Comment by selvanair** [comment]
cd openvpn-<version>
after tar -zxf ...
is missing..

**Comment by mattock** [comment]
Indeed, and this is why using GitHub for review is so much easier than the mailing list :). V3 of this seemingly trivial patch is now on the list.

**Comment by cron2** [comment]
seems as if this has been merged, right?

**Pull request closed without merging**
