### PR TITLE
testing: Refactor t client.sh

### PR DESCRIPTION
**Pull request by neuhalje**
Move global code into separate functions. Fixup formatting of code. Also add table output formatting to t_client.sh:

``` text
| ID | TEST                                | RESULT               |
| -- | ----------------------------------- | -------------------- |
|  1 | testing tun/udp/ipv4                | [SUCCESS]            |
|  2 | testing tun/udp/ipv4 with pam       | [FAIL: 5 fails]      |
| -- | ----------------------------------- | -------------------- |
Test sets succeded: 1.
Test sets failed: 2.
```

For easier review these patches have also been provided via GitHub pull request: 
https://github.com/OpenVPN/openvpn/pull/49

Due to moving code around and intention changes this patch looks rather large:
 1 file changed, 267 insertions(+), 180 deletions(-).

### CODE REVIEW

**Comment by neuhalje** [comment]
TODO: make sure that it works on

* Ubuntu Precise Pangolin
* Mac OS
* Solaris 11

**Comment by neuhalje** [comment]
Solaris 11.3 works if I manually change the shell in the shebang to `#!/bin/bash`

**Comment by cron2** [comment]
Hi,

On Mon, May 23, 2016 at 08:54:27AM -0700, Jens Neuhalfen wrote:
> Solaris 11.3 works if I manually change the shell in the shebang to `#bin/bash`

If we do that from autoconf, fine with me - /bin/bash seems to be
installed "out of the factory" on Solaris.  

It will *not* be there on the BSDs by default, so we can't change it
by default (and if installed, it will be /usr/local/bin/bash).

gert
-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by neuhalje** [comment]
@cron2 What are the 'modern'  shells on BSDs? It honestly feels a bit strange to restrict ourselves to a DEV environment older than 20 years.

**Comment by cron2** [comment]
Hi,

On Mon, May 23, 2016 at 09:17:56AM -0700, Jens Neuhalfen wrote:
> @cron2 What are the 'modern'  shells on BSDs? It honestly feels a bit strange to restrict ourselves to a DEV environment older than 20 years.

BSD is "POSIX shell" (or perl since autoconf pulls that in anyway).

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by chipitsine** [comment]
Jens, please have a look at this https://travis-ci.org/OpenVPN/openvpn/jobs/135835676

**Comment by mattock** [comment]
Another quoting issue? It seems the tests tried to run "openvpn --genkey" and failed.

**Comment by chipitsine** [comment]
openvpn was configured --disable-crypto, it is legitimate configuration, we should not fail "make check" on that

**Comment by syzzer** [comment]
@chipitsine: that needs to fixed indeed, but is not related to this pull request.

**Comment by chipitsine** [comment]
ok

**Comment by mattock** [comment]
The "Fix formatting of code" part makes the GitHub diff mostly useless. That can be solved by downloading a patch for this PR:

    cd openvpn
    wget https://github.com/OpenVPN/openvpn/pull/49.patch
    git am 49.patch
    git show -b -2

The -b flag ignores whitespace changes and makes the changes much more readable.

I skimmed through the changes, but without testing it's difficult to see if they're correct or not. Cron2: have you tested this PR already?

I agree with cron2 that t_client.sh needs to be kept free of bashisms. Are there any in the new code, and if yes, can't they be solved with in a POSIX-compliant fashion?

**Comment by neuhalje** [comment]
4 years ... this is probably dead by now

**Comment by mattock** [comment]
@neuhalje I think so - it is unlikely this would get merged now if it was not merged four years ago.

**Pull request closed without merging**
