### PR TITLE
[PATCH v2] Insert client connection data into PAM environment

### PR DESCRIPTION
**Pull request by wardragon**
Without this patch, the PAM enviornment lacks any information about the remote client address.

syslog output for auth and authpriv facilities changes
from:
   Oct 25 11:52:02 openvpndev openvpn: pam_unix(openvpn:auth): authentication failure;
                   logname=root uid=0 euid=0 tty= ruser= rhost=
   Oct 25 11:52:33 openvpndev openvpn: pam_unix(openvpn:auth): authentication failure;
                   logname=root uid=0 euid=0 tty= ruser= rhost=  user=****
to:
   Oct 25 10:56:11 openvpndev openvpn: pam_unix(openvpn:auth): authentication failure;
                   logname=root uid=0 euid=0 tty= ruser= rhost=198.51.100.10
   Oct 25 10:57:02 openvpndev openvpn: pam_unix(openvpn:auth): authentication failure;
                   logname=root uid=0 euid=0 tty= ruser= rhost=198.51.100.10 user=****

Furthermore, the presence of the remote client address in PAM
environment, enables usage of pam modules like pam_recent
[https://github.com/az143/pam_recent].

Replaces #71

### CODE REVIEW

**Comment by pulecp** [comment]
What's the status of this? I also woke up the thread in #71. See [link](https://github.com/OpenVPN/openvpn/pull/71#issuecomment-1135886474).

**Comment by ordex** [comment]
Closing as it seems to be superseded by #175

**Comment by cron2** [comment]
Hi,

On Tue, May 24, 2022 at 05:57:07AM -0700, Pavel Pulec wrote:
> What's the status of this? I also woke up the thread in #71. See [link](https://github.com/OpenVPN/openvpn/pull/71#issuecomment-1135886474).

Looking at the mailing list, we seem to be still waiting for a patch
that arrives in one piece (sent by "git send-email", not as an attachment
- too many mail clients break whitespace badly, making the patch not
applicable anymore) and takes review feedback into account.

Until then, it cannot progress.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by selvanair** [comment]
This is same as what was merged the other day, isn't it? 

```
commit 8e9f9d031f7f2dbf2a505af297b808f22430a381
Author: Paolo Cerrito <paolo.cerrito@uniroma2.it>
Date:   Mon Oct 10 14:27:46 2022 +0200

    Insert client connection data into PAM environment
```

**Comment by cron2** [comment]
Hi,

On Tue, Oct 11, 2022 at 08:09:37AM -0700, Selva Nair wrote:
> This is same as what was merged the other day, isn't it? 
> 
> ```
> commit 8e9f9d031f7f2dbf2a505af297b808f22430a381
> Author: Paolo Cerrito ***@***.***>
> Date:   Mon Oct 10 14:27:46 2022 +0200
> 
>     Insert client connection data into PAM environment
> ```

Yes, that patch hit the list and github a few times :-) - so all
occurences that you can find can be closed now.

thanks

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by Rojov1vo** [comment]
Hi

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rojov1vo** [comment]
What merge

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rojov1vo** [comment]
Why

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
