### PR TITLE
Add timeout option for socks proxies

### PR DESCRIPTION
**Pull request by nferch**

### CODE REVIEW

**Comment by schwabe** [comment]
I think my proposed patch (http://mid.gmane.org/1444919912-4432-1-git-send-email-arne@rfc2549.org) implements this in a better way.

**Comment by cron2** [comment]
@schwabe is this already solved in some way, or will it be solved as soon as The Big Timeout Patch is merged?

**Comment by schwabe** [comment]
@cron2 No the timeout patch removes the socks-proxy-timeout and integrates it into the big timeout

**Comment by dsommers** [comment]
As I understand it, commit f2134b7bea37df15756c599b94f16d4bffafbbd6 seems to be resolving this issue.  So closing this one.

**Pull request closed without merging**
