### PR TITLE
fix typo CVE

### PR DESCRIPTION
**Pull request by attritionorg**
# Thank you for your contribution

You are welcome to open PR, but they are used for discussion only. All
patches must eventually go to the openvpn-devel mailing list for review:

* https://lists.sourceforge.net/lists/listinfo/openvpn-devel

Please send your patch using [git-send-email](https://git-scm.com/docs/git-send-email). For example to send your latest commit to the list:

    $ git send-email --to=openvpn-devel@lists.sourceforge.net HEAD~1

For details, see these Wiki articles:

* https://community.openvpn.net/openvpn/wiki/DeveloperDocumentation
* https://community.openvpn.net/openvpn/wiki/Contributing

### CODE REVIEW

**Comment by ordex** [comment]
Can you please send this patch to the openvpn-devel mailing list, after having added a Signed-off-by line?

**Comment by cron2** [comment]
Hi,

On Thu, Dec 23, 2021 at 12:06:33AM -0800, Antonio Quartulli wrote:
> Can you please send this patch to the openvpn-devel mailing list, after having added a Signed-off-by line?

I can forward the patch to the list, and for documentation fixes, we
can live without a Signed-off-by: - but it is missing a proper Author:,
so it cannot go in as-is

Author: Jericho ***@***.***>

-> please commit with correct author settings (Name + e-mail), and
either push again to the PR, or send to the list.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by attritionorg** [comment]
Please submit the correction as yourself, not from me then. This is a lot of bureaucracy for a single typo in a CVE that causes confusion for your users.

**Comment by cron2** [comment]
Hi,

On Mon, Dec 27, 2021 at 08:58:50AM -0800, Jericho wrote:
> Please submit the correction as yourself, not from me then. This is a lot of bureaucracy for a single typo in a CVE that causes confusion for your users.

As I said, we can live without the signed-off-by for a simple patch -
for a more complex patch, this is required (as it signals acceptance
of the license etc.).  We do need a proper author name - if only to
give credits where credits are due.

As requested, I've now submitted a patch on my own, fixing the OpenSSL 
path in the 2.5.5 release notes in the same go.

thanks for your PR!

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by flichtenheld** [comment]
Change has been merged.

**Pull request closed without merging**
