### PR TITLE
--server-ipv6 parsing error display wrong arg

### PR DESCRIPTION
**Pull request by cacamille3**
# Thank you for your contribution

You are welcome to open PR, but they are used for discussion only. All
patches must eventually go to the openvpn-devel mailing list for review:

* https://lists.sourceforge.net/lists/listinfo/openvpn-devel

Please send your patch using [git-send-email](https://git-scm.com/docs/git-send-email). For example to send your latest commit to the list:

    $ git send-email --to=openvpn-devel@lists.sourceforge.net HEAD~1

For details, see these Wiki articles:

* https://community.openvpn.net/openvpn/wiki/DeveloperDocumentation
* https://community.openvpn.net/openvpn/wiki/Contributing

### CODE REVIEW

**Comment by ordex** [comment]
Thanks for spotting this and for writing a fix!
Caould you please add a Signed-off-by line to your commit and send your patch to the openvpn-devel mailing list for review?
Thanks!

ml: https://lists.sourceforge.net/lists/listinfo/openvpn-devel

**Comment by cacamille3** [comment]
Actually the fix should be different...

`else if (streq(p[0], "server-ipv6") && p[1] && !p[3])` 

Should be replaced with 

`else if (streq(p[0], "server-ipv6") && p[1] && !p[2])` 

and then the following could be removed.

```
        if (p[2])       /* no "nopool" options or similar for IPv6 */
        {
            msg(msglevel, "error parsing --server-ipv6: %s is not a recognized flag", p[2]);
            goto err;
        }
```

What do you think ?

**Comment by ordex** [comment]
@cacamille3 that would not be a "fix", but rather a change in behaviour.
The idea behind that error message is that some people expect to be able to pass to `--server-ipv6` the same flags as `--server`. For this reason I'd still keep the message as is, so that people moving to `--server-ipv6` are warned about the difference.
Does it make sense to you?

In any case, I'd still submit the fix as proposed originally. Additionally to that you may open a discussion about the change in behaviour on the mailing list, if you want other opinions. This is just mine of course :-)

**Comment by selvanair** [comment]
> @cacamille3 that would not be a "fix", but rather a change in behaviour. The idea behind that error message is that some people expect to be able to pass to `--server-ipv6` the same flags as `--server`. For this reason I'd still keep the message as is, so that people moving to `--server-ipv6` are warned about the difference. Does it make sense to you?

Does not make sense to me :)

Given that the original code printed an unhelpful message (printing p[3], which is NULL, instead of p[2]), I would say this was not serving any useful purpose in the first place. If the intent was to make the syntax of --server-ipv6 match --server, the additional arg should have been ignored with a warning, not  a fatal error.

So I would say, the proposed (corrected) patch with p[1] && !p[2] is the appropriate fix.

As a more general note, when an option parse error is reported, printing the whole option line or the token that caused the error may be useful for all options, not just this one. Currently we only print the option name that caused the error. But that's beyond this patch.

**Comment by ordex** [comment]
@selvanair sure, that makes sense. From a history/patch perspective I'd just prefer to split the two changes, but you're right that at the moment there is nothing that really needs fixing as the message has always been bogus.

Let's go with "p[1] && !p[2]" directly then.

@cacamille3 would you send the patch to the mailing list?

Thanks!

**Comment by cacamille3** [comment]
@ordex Done ✅

**Comment by cron2** [comment]
Hi,

On Wed, Dec 15, 2021 at 02:11:56AM -0800, Camille Guérin wrote:
> @ordex Done ???

Never showed up on the list...  so I've re-sent it today, squashed
both changes into one single patch.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Pull request closed without merging**
