### PR TITLE
duplicate function declaration.

### PR DESCRIPTION
**Pull request by 20150723**
# Thank you for your contribution

You are welcome to open PR, but they are used for discussion only. All
patches must eventually go to the openvpn-devel mailing list for review:

* https://lists.sourceforge.net/lists/listinfo/openvpn-devel

Please send your patch using [git-send-email](https://git-scm.com/docs/git-send-email). For example to send your latest commit to the list:

    $ git send-email --to=openvpn-devel@lists.sourceforge.net HEAD~1

For details, see these Wiki articles:

* https://community.openvpn.net/openvpn/wiki/DeveloperDocumentation
* https://community.openvpn.net/openvpn/wiki/Contributing

### CODE REVIEW

**Comment by cron2** [comment]
Hi,

good find.  

Please send the patch to the mailing list, as the PR docs say.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by 20150723** [comment]
OK

1. patch has been sent, If you have any questions, please contact me.

**Comment by 20150723** [comment]
Thanks,

Message has been sent.
Use sendmail for the first time, please contact me if you have any questions.

**Comment by cron2** [comment]
Hi,

On Wed, Jun 02, 2021 at 10:17:57PM -0700, Jeff wrote:
> 1. patch has been sent, If you have any questions, please contact me.

Patch has not arrived on the list.

You can always check the list archives under 

  ***@***.***/

to see if your patch made it correctly.

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by cron2** [comment]
Patch has been merged via our "send to openvpn-devel to get it reviewed and merged" process.

Thanks for your contribution.

**Pull request closed without merging**
